const extraLevel = [
    {   level: 13,
        question: '26 września 1908 r. pod Bezdanami na Litwie czterech przyszłych polskich premierów:',
        answers: ['Wystąpiło na forum ONZ', 'Zagrało w orkiestrze', 'Obrabowało pociąg pocztowy', 'Znalazło wybranki'],
        public: [34,30,34,2],
        correctAnswer: 'Obrabowało pociąg pocztowy',
    },
    {   level: 13,
        question: 'Bantustan, to wydzielony obszar dla grup czarnoskórej ludności powstały w latach 60. na terenie:',
        answers: ['Somalii', 'Etiopii', 'RPA', 'Konga'],
        public: [31,31,36,2],
        correctAnswer: 'RPA',
    },
    {   level: 13,
        question: 'Godło którego państwa zaprojektował jeden z czołowych przedstawicieli secesji Alfons Mucha?',
        answers: ['Jugosławii', 'Czechosłowacji', 'ZSRR', 'NRD'],
        public: [31,37,30,2],
        correctAnswer: 'Czechosłowacji',
    },
    {   level: 13,
        question: '30 X 1918 r. proklamowano utworzenie jednego z pierwszych skrawków wolnej Polski z prezydentem Stefanem Żeromskim. Chodzi o:',
        answers: ['Kraj Pucki', 'Rzeczpospolitą Zakopiańską', 'Królestwo Kurpiowskie', 'Polskę Kaszubską'],
        public: [31,37,30,2],
        correctAnswer: 'Rzeczpospolitą Zakopiańską',
    },
    {   level: 13,
        question: 'Co jest podstawą diety osich czerwi?',
        answers: ['Pyłek kwiatów', 'Owady', 'Rosa miodowa', 'Spadź'],
        public: [31,37,30,2],
        correctAnswer: '',
    },
    {   level: 13,
        question: 'Od czego pochodzi nazwa zespołu Kwiat Jabłoni, założonego w 2018 r. przez Katarzynę i Jacka Sienkiewiczów?',
        answers: ['Od snobistycznego klubu', 'Od kiczowatego obrazu', 'Od luksusowego auta', 'Od taniego wina'],
        public: [31,30,1,38],
        correctAnswer: 'Od taniego wina',
    },
    
]
export {extraLevel};