const level11 = [
    {   level: 11,
        question: 'Jedlina, świerczyna i podobne to:',
        answers: ['ubierasz', 'stroisz', 'ozdabiasz', 'robisz się na bóstwo'],
        public: [31,37,30,2],
        correctAnswer: 'stroisz',
    },
    {   level: 11,
        question: '„Kto prosił ruskie” - to początek godzącego w sojusze popularnego żartu z baru mlecznego. Jak brzmi odpowiedź?',
        answers: ['„Leniwe prosiły”', '„Nikt. Same przyszły”', '„Komorowski z Tuskiem”', '„Balcerowicz z Buzkiem”'],
        public: [41,50,4,5],
        correctAnswer: '„Nikt. Same przyszły”',
    },
    {   level: 11,
        question: 'Manat karaibski, tak jak afrykański, z kończyn ma tylko przednie. A manat azerbejdżański, tak jak turkmeński:',
        answers: ['zastąpił rubla', 'ma i przednie, i tylne', 'zakrywa całe ciało', 'jest samotnikiem'],
        public: [61,19,11,9],
        correctAnswer: 'zastąpił rubla',
    },
    {   level: 11,
        question: 'Galinstan, stop galu, indu i cyny, zastąpił:',
        answers: ['złoto w obrączkach', 'rtęć w termometrach', 'miedzionikiel w złotówkach', 'amalgamat w plombach'],
        public: [9,49,11,31],
        correctAnswer: 'rtęć w termometrach',
    },
    {   level: 11,
        question: '„Mona Lisa” z Luwru to obraz namalowany:',
        answers: ['na tkaninie', 'na metalu', 'na drewnie', 'na murze'],
        public: [46,1,49,4],
        correctAnswer: 'na drewnie',
    },
    {   level: 11,
        question: 'U Mickiewicza: „Obszar gnuśności zalany odmętem”...',
        answers: ['To Polska!', 'To Rosja!', 'To Austro-Węgry!', 'To Ziemia!'],
        public: [7,16,11,66],
        correctAnswer: 'To Ziemia!',
    },
    
]
export {level11};