const level10 = [
    {   level: 10,
        question: 'Z którym z kwiatów najczęściej portretowano Mikołaja Kopernika?',
        answers: ['z lilią', 'z szarotką', 'z mniszkiem lekarskim', 'z konwalią'],
        public: [9,28,27,36],
        correctAnswer: 'z konwalią',
    },
    {   level: 10,
        question: 'Pierwszego przeszczepu serca dokonano u człowieka w XX w. w latach:',
        answers: ['trzydziestych', 'sześćdziesiątych', 'osiemdziesiątych', 'dziewięćdziesiątych'],
        public: [9,31,30,30],
        correctAnswer: 'sześćdziesiątych',
    },
    {   level: 10,
        question: 'Annasz to żydowski arcykapłan z czasów Chrystusa. Kim był dla niego Kajfasz?',
        answers: ['zięciem', 'teściem', 'dziadkiem', 'pradziadkiem'],
        public: [15,34,29,22],
        correctAnswer: 'teściem',
    },
    {   level: 10,
        question: 'Zbyszek wczoraj ukończył 15 lat, ale już zna się na prawie i wie, że mógłby być sądzony na podstawie Kodeksu karnego za:',
        answers: ['obnażanie się w parku', 'łapownictwo wyborcze', 'szpiegostwo', 'wzięcie zakładnika'],
        public: [19,4,38,39],
        correctAnswer: 'wzięcie zakładnika',
    },
    {   level: 10,
        question: 'Taksówkarz ma pasażerów, lekarz pacjentów, spowiednik penitentów, sprzedawca klientów. A prawnik?',
        answers: ['mandatów', 'mandatariuszy', 'mandatariuszy', 'notariuszy'],
        public: [15,42,39,4],
        correctAnswer: 'mandatariuszy',
    },
    {   level: 10,
        question: 'Albert Einstein był obdżektorem. Kto jeszcze?',
        answers: ['Winston Churchill', 'Bronisław Cieślak', 'Maciej Maleńczuk', 'Andrzej Gajos'],
        public: [9,19,43,29],
        correctAnswer: 'Maciej Maleńczuk',
    },
    
]
export {level10};