const level9 = [
    {   level: 9,
        question: 'Petrol to barwa powstała z połączenia dwóch kolorów:',
        answers: ['niebieskiego i zielonego', 'jasno- i ciemnobrązowego', 'złotego i srebrnego', 'białego i czarnego'],
        public: [73,11,15,1],
        correctAnswer: 'niebieskiego i zielonego',
    },
    {   level: 9,
        question: ' Żydówka z obrazu Aleksandra Gierymskiego, odzyskana przez Polskę w 2011 r., zajęta jest:',
        answers: ['obieraniem pomarańczy', 'robieniem na drutach', 'liczeniem banknotów', 'rozsypywaniem okruszków'],
        public: [34,40,6,20],
        correctAnswer: 'robieniem na drutach',
    },
    {   level: 9,
        question: 'Który z wyrazów to rodzaj gitary akustycznej?',
        answers: ['odwaga', 'dobro', 'rytm', 'smutek'],
        public: [9,33,29,29],
        correctAnswer: 'dobro',
    },
    {   level: 9,
        question: 'W którym z miast znajduje się pomnik mający postać 2711 betonowych bloków ustawionych w równoległych rzędach?',
        answers: ['w Londynie', 'w Berlinie', 'w Moskwie', 'w Nowym Jorku'],
        public: [23,40,30,7],
        correctAnswer: 'w Berlinie',
    },
    {   level: 9,
        question: 'Tkanina na mundury to:',
        answers: ['adamaszek', 'gabardyna', 'satyna', 'mora'],
        public: [11,41,9,39],
        correctAnswer: 'gabardyna',
    },
    {   level: 9,
        question: 'Kto jako pierwszy skonstruował i oblatał pasażerski samolot ponaddźwiękowy?',
        answers: ['Amerykanie', 'Francuzi i Anglicy', 'Rosjanie', 'Holendrzy i Belgowie'],
        public: [36,19,36,9],
        correctAnswer: 'Rosjanie',
    },
    {   level: 9,
        question: 'Który aktor podbija muzyczną scenę depresyjnym "rock and rollem bez przebaczenia"?',
        answers: ['Marian Dziędziel', 'Arkadiusz Jakubik', 'Bartłomiej Topa', 'Robert Więckiewicz'],
        public: [9,64,7,20],
        correctAnswer: 'Arkadiusz Jakubik',
    },
    
]
export {level9};