const level12 = [
    {   level: 12,
        question: 'Który utwór Juliusza Słowackiego napisany jest prozą?',
        answers: ['„Godzina myśli"', 'W Szwajcarii"', '„Arab"', '„Anhelli"'],
        public: [11,34,19,36],
        correctAnswer: '„Anhelli"',
    },
    {   level: 12,
        question: 'Płetwą grzbietową nie pruje wody:',
        answers: ['kosogon', 'wal grenlandzki', 'orka', 'długoszpar'],
        public: [10,37,19,34],
        correctAnswer: 'wal grenlandzki',
    },
    {   level: 12,
        question: 'Kto był nadwornym malarzem króla Filipa IV Habsburga?',
        answers: ['Jan van Eyck', 'Diego Velázquez', 'Marcello Bacciarelli', 'Jacques-Louis David'],
        public: [30,37,29,4],
        correctAnswer: 'Diego Velázquez',
    },
    {   level: 12,
        question: 'Mowa w obronie poety Archiasza przeszła do historii jako jeden z najświetniejszych popisów retorycznych:',
        answers: ['Demostenesa', 'Cycerona', 'Izokratesa', 'Kwintyliana'],
        public: [19,41,39,1],
        correctAnswer: 'Cycerona',
    },
    {   level: 12,
        question: 'Kto jest mistrzem tego samego oręża, w jakim specjalizowała się mitologiczna Artemida?',
        answers: ['Legolas', 'Zorro', 'Don Kichot', 'Longinus Podbipięta'],
        public: [40,5,24,31],
        correctAnswer: 'Legolas',
    },
    {   level: 12,
        question: 'Rybą nie jest:',
        answers: ['kraska', 'krasnopiórka', 'świnka', 'rozpiór'],
        public: [39,15,29,17],
        correctAnswer: 'kraska',
    },
    {   level: 12,
        question: 'Komiksowym "dzieckiem" rysownika Boba Kane`a jest:',
        answers: ['Spider-Man', 'Batman', 'Superman', 'Captain America'],
        public: [14,35,40,11],
        correctAnswer: 'Batman',
    },
    {   level: 12,
        question: 'Skąd pochodzi Conan Barbarzyńca?',
        answers: ['z Rivii', 'z Oz', 'z Mordoru', 'z Cimmerii'],
        public: [29,9,26,36],
        correctAnswer: 'z Cimmerii',
    },
    
]
export {level12};